---
# tasks file for win_service_config

#Install an array of packages using the win_chocolatey when the distro is server 2012 r2
- name: Install Windows packages
  win_chocolatey:
    name: "{{ package_name }}"
    params: "{{ parameters }}"
    state: latest
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"

#accepts a 'service_name' variable and starts it when the distro is server 2012 r2
- name: Start windows services
  win_service:
    name: "{{ service_name }}"
    state: started
    start_mode: auto
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"

#create firewall rules based on ' service_name ' variable
- name: Setup windows firewall
  win_firewall_rule:
    name: "{{ service_name }}"
    localport: "{{ local_port }}"
    action: allow
    direction: in
    protocol: "{{ protocol_name }}"
    state: present
    enabled: yes
