---
# tasks file for win_service_config

#accepts a 'service_name' variable and starts it when the distro is server 2012 r2
- name: Start windows services
  win_service:
    name: "{{ item.name }}"
    state: started
    start_mode: auto
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"
  with_items:
    - "{{ win_services }}"
